apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-platform
  namespace: ai-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-platform
  template:
    metadata:
      labels:
        app: ai-platform
    spec:
      containers:
      - name: ai-platform
        image: my-ai-platform:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-platform-service
  namespace: ai-platform
spec:
  selector:
    app: ai-platform
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
